package com.khweditech.fixme.router;

import com.khweditech.BuyDB;
import com.khweditech.SellDB;
import com.khweditech.MessagesHub;
import com.khweditech.fixme.broker.controllers.BrokerController;
import com.khweditech.fixme.market.controllers.MarketController;
import com.khweditech.fixme.router.controllers.RouterController;

import javax.swing.*;

public class LandingPage extends javax.swing.JFrame {

    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnStartRouter = new javax.swing.JButton();
        btnStartMarket = new javax.swing.JButton();
        btnStartBroker = new javax.swing.JButton();
        btnStopRouter = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        txtQtn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPortID = new javax.swing.JTextField();
        txtOpt = new javax.swing.JTextField();
        btnStopMarket = new javax.swing.JButton();
        btnStopBroker = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRouter = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMarket = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBroker = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fixme");

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setText("FIXME Protol");

        btnStartRouter.setText("Start / Print");
        btnStartRouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartRouterActionPerformed(evt);
            }
        });

        btnStartMarket.setText("Start Market");
        btnStartMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartMarketActionPerformed(evt);
            }
        });

        btnStartBroker.setText("Start Broker");
        btnStartBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartBrokerActionPerformed(evt);
            }
        });

        btnStopRouter.setText("Stop Router");
        btnStopRouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopRouterActionPerformed(evt);
            }
        });

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        txtQtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantity");

        jLabel3.setText("Price");

        jLabel4.setText("Port ID");

        jLabel5.setText("Option");

        txtPortID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortIDActionPerformed(evt);
            }
        });

        txtOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOptActionPerformed(evt);
            }
        });

        btnStopMarket.setText("Stop Market");
        btnStopMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopMarketActionPerformed(evt);
            }
        });

        btnStopBroker.setText("Stop Broker");
        btnStopBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopBrokerActionPerformed(evt);
            }
        });

        txtRouter.setColumns(20);
        txtRouter.setRows(5);
        jScrollPane1.setViewportView(txtRouter);

        txtMarket.setColumns(20);
        txtMarket.setRows(5);
        jScrollPane2.setViewportView(txtMarket);

        txtBroker.setColumns(20);
        txtBroker.setRows(5);
        jScrollPane3.setViewportView(txtBroker);

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel6.setText("Router");

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel7.setText("Market");

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel8.setText("Broker");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnStartMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(392, 392, 392)
                                                .addComponent(jLabel7)
                                                .addGap(461, 461, 461)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtQtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnStopMarket, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnStartBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(382, 382, 382)
                                                .addComponent(jLabel8)
                                                .addGap(470, 470, 470)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtPortID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtOpt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnStopBroker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane3)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnStartRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(391, 391, 391)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnStopRouter, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnStartRouter)
                                        .addComponent(jLabel6)
                                        .addComponent(btnStopRouter))
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnStartMarket)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnStopMarket)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtPortID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnStartBroker)
                                                        .addComponent(btnStopBroker))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void btnStartRouterActionPerformed(java.awt.event.ActionEvent evt) {
        String host = "localhost";
        int port = 5000;
        RouterController router = new RouterController(host, port);
        router.startServers();

        SellDB.getSellMessage();
        BuyDB.getRouterMessage();

        txtRouter.append(MessagesHub.msgDBconnected+'\n');
        txtRouter.append(MessagesHub.msgStartRouterBroker +'\t'+ MessagesHub.msgStartRouterMarket+'\n');

        txtRouter.append(MessagesHub.msgGetServerNameBroker+'\n');
        txtRouter.append(MessagesHub.msgGetServerNameMarket+'\n');

        txtRouter.append(MessagesHub.msgServerPortName+'\n');
        txtRouter.append(MessagesHub.msgAcceptedClientConn+'\n');

    }

    private void btnStartMarketActionPerformed(java.awt.event.ActionEvent evt) {
        MarketController market = new MarketController(Integer.parseInt(txtQtn.getText()),
                Integer.parseInt(txtPrice.getText()));
       try {
            market.startClient();
            txtMarket.append(MessagesHub.msgStartMarketClient+'\n');

            txtMarket.append(MessagesHub.msgCompletedMarketResponedID+'\n');

            txtMarket.append(MessagesHub.msgCompletedMarketResponed+'\n');
            txtMarket.append(MessagesHub.msgCompleteMarketResponse+'\n');

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void btnStartBrokerActionPerformed(java.awt.event.ActionEvent evt) {
        BrokerController broker = new BrokerController(Integer.parseInt(txtPortID.getText()),
                Integer.parseInt(txtOpt.getText()));
        SellDB.getSellMessage();
        BuyDB.getRouterMessage();
        try
        {
            broker.startClient();
            txtBroker.append(MessagesHub.msgBrokerConnected+'\n');
            txtBroker.append(MessagesHub.msgBrokerServerResponded+'\n');
            txtBroker.append(MessagesHub.msgBrokerResponse+'\n');
            txtMarket.append(MessagesHub.msgCompletedMarketResponedID+'\n');
            txtMarket.append(MessagesHub.msgCompleteMarketResponse+'\n');

            txtMarket.append(MessagesHub.msgCompletedBrokerResponse+'\n');

            txtRouter.append(MessagesHub.msgGetServerNameBroker+'\n');

            txtBroker.append(MessagesHub.msgProccessReplyRejected+'\n');
            txtBroker.append(MessagesHub.msgProccessReplyAccepted+'\n');
        }
        catch(Exception e)
        { }
    }

    private void btnStopMarketActionPerformed(java.awt.event.ActionEvent evt) {
        String errors = MessagesHub.msgCompletedError;
        String headsUp = "Mandatory part\n" +
                "You need to implement simulation tools for the financial markets that exchange a simplified\n" +
                "version of FIX messages. The tools will be able to communicate over a network\n" +
                "using the TCP protocol.The focus in this project are not the trading algos (you can\n" +
                "experiment with them after the project is finished), but the implementation of a robust\n" +
                "and performant messaging platform.";

        JOptionPane.showMessageDialog(null, headsUp + " Errors, if any " + errors);
    }

    private void btnStopRouterActionPerformed(java.awt.event.ActionEvent evt) {

        System.exit(1);
    }

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtQtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPortIDActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtOptActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnStopBrokerActionPerformed(java.awt.event.ActionEvent evt) {
        String errors = MessagesHub.msgCompletedError;
        String headsUp = "Mandatory part\n" +
                "You need to implement simulation tools for the financial markets that exchange a simplified\n" +
                "version of FIX messages. The tools will be able to communicate over a network\n" +
                "using the TCP protocol.The focus in this project are not the trading algos (you can\n" +
                "experiment with them after the project is finished), but the implementation of a robust\n" +
                "and performant messaging platform.";

        JOptionPane.showMessageDialog(null, headsUp + " Errors, if any " + errors);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        String host = "localhost";
        int port = 5000;

        if (args.length == 0){
            RouterController router = new RouterController(host, port);
            router.startServers();
        }else
            System.out.println("Please reRun the program without args[1]");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnStartBroker;
    private javax.swing.JButton btnStartMarket;
    private javax.swing.JButton btnStartRouter;
    private javax.swing.JButton btnStopBroker;
    private javax.swing.JButton btnStopMarket;
    private javax.swing.JButton btnStopRouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtBroker;
    private javax.swing.JTextArea txtMarket;
    private javax.swing.JTextField txtOpt;
    private javax.swing.JTextField txtPortID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQtn;
    private javax.swing.JTextArea txtRouter;
    // End of variables declaration
}
